### ISSUE TITLE
ABMX issue with modboneimplantor in chara maker and free h (KK)

### ISSUE THREAD

**Issue by Alv4rna** [ManlyMarco/ABMX#42] opened 2022-11-28 06:23 UTC
When bones implanted with modboneimplantor edited in maker with abmx, it changed properly. But, when the maker is reopen in another session, the abmx edits is not applied immediately. Only after the outfit is changed to another set and back to it again, abmx is applied. This also happened in free h mode, but didn't happen in studio (abmx applied immediately after spawning the character).

**Comment by ManlyMarco** [comment] 2022-12-25 21:56
Duplicate of #28

**Closed by ManlyMarco** 2022-12-25 21:56 UTC
Labels: bug
