### ISSUE TITLE
Genitals scale defaults for females

### ISSUE THREAD

**Issue by IDontHaveIdea** [ManlyMarco/ABMX#32] opened 2021-12-03 18:01 UTC
It would be good to be able to change the scale default for the genitals penis, penis tip and testicles through configuration for the females.  This will help in cases like BetterPenetration when the uncensors have colliders it will create the effect of a phantom penis and deforms the skirts in maker and to various degrees in game.

This happens as long there is a penis uncensor with colliders in the mods even when the plugin is not been used.

The process of doing it manually is kind of tedious and easy to forget if in maker when you work the coordinate shown does not present the issue.

**Comment by ManlyMarco** [comment] 2021-12-03 19:06
Update BP and its uncensors to fix the collider issue.

**Comment by ManlyMarco** [comment] 2022-11-05 08:38
It's now possible to save/load presets in advanced UI, and hopefully the issue is fixed in BP already.

**Closed by ManlyMarco** 2022-11-05 08:38 UTC
